Documentation for how to specify mag and color cuts for supplemented ASTs
BEAST-Fitting/beast pull request #657
Opened 2020-11-03 19:14 UTC by cmurray-astro

In the docstring to the supplement_ast() function in make_ast_input_list.py, I added descriptions and examples of how to set the correct parameters in the beast_settings.txt file for making magnitude and color cuts to supplemented ASTs. I will also add this to the template beast_settings.txt file (which is stored in beast_examples).

@galaxyumi and @kmcquinn please let me know what you think! Based on your feedback, I can make this more user-friendly and/or intuitive, especially if you run into issues/bugs.

2020-11-03 19:35 UTC, cmurray-astro commented
also added descriptions to the generating_asts docs page!

2020-11-03 19:35 UTC, galaxyumi requested changes
Once the typos are fixed, it seems all good to me!

2020-11-03 19:35 UTC, galaxyumi commented on beast/observationmodel/ast/make_ast_input_list.py
> +        ast_suppl_colorlimits["HST_WFC3_F475W"] = [["HST_WFC3_F814W",4]]
To be consistent with the above description, it should be ast_suppl_colorlimits["HST_WFC3_F475W"] = [["HST_WFC3_F814W",6]]
ast_suppl_colorlimits["HST_WFC3_F336W"] = [["HST_WFC3_F475W",5], ["HST_WFC3_F814W",4]]

2020-11-03 19:35 UTC, galaxyumi commented on beast/observationmodel/ast/make_ast_input_list.py
> +        Dictionary of faint color limits for given filters.
How about 'red'?

2020-11-03 19:35 UTC, galaxyumi commented on docs/generating_asts.rst
> +    ast_suppl_colorlimits["HST_WFC3_F475W"] = [["HST_WFC3_F814W",4]]
Same comment for the beast/observationmodel/ast/make_ast_input_list.py.
ast_suppl_colorlimits["HST_WFC3_F475W"] = [["HST_WFC3_F814W",6]]
ast_suppl_colorlimits["HST_WFC3_F336W"] = [["HST_WFC3_F475W",5], ["HST_WFC3_F814W",4]]

2020-11-03 19:35 UTC, kmcquinn commented
I think the documentation you sent is clear. But I'm having trouble intergrating that with existing documentation. For example, there is a detailed description of making AST lists here:
https://beast.readthedocs.io/en/latest/generating_asts.html 
But I can't reconcile it with the beast_settings.txt documentation here:
https://beast.readthedocs.io/en/latest/beast_setup.html#beast-setup-settings

Perhaps I'm just missing something?

2020-11-03 19:42 UTC, cmurray-astro commented
@kmcquinn good point -- the beast_settings documentation (https://beast.readthedocs.io/en/latest/beast_setup.html#beast-setup-settings) looks like a summary of all the settable parameters, without much guidance on how and when to use them (and also looks out of date!). I can open an issue about this.

2020-11-10 15:24 UTC, kmcquinn commented
I'm working on testing the code to run MATCH-optimized ASTs and I realized that I'm not clear on how to specify ast_suppl_colorlimits.  If, for example, you have 4 filters, how do you specify the colorlimits variable? Do you need to list all different filter combinations with color limits? Would you be able to post an example of this should be done? Thanks!

2020-11-10 15:32 UTC, cmurray-astro commented
@kmcquinn currently the way it works is you have to specify whichever color limits you want to impose. this PR includes documentation but hasn't been merged yet, so if you check out the "files changed" you can see the examples. the color limit example is here: 

        For example, for a field observed with HST_WFC3_F336W, HST_WFC3_F475W,
        and HST_WFC3_F814W, to set a color range limit of HST_WFC3_F475W-HST_WFC3_F814W<6,
        HST_WFC3_F336W-HST_WFC3_F475W<5 and HST_WFC3_F336W-HST_WFC3_F814W<4, you need
        to set the following within the beast_settings file:

        # specify that the ast_supplement mode should be on
        ast_supplement = True

        # initialize the dictionary of desired magnitude limits
        ast_suppl_colorlimits = {}

        # the color limits are defined by the first filter in the color (e.g, X for X-Y),
        # and the input is a list including the second filter (e.g., Y for X-Y) and the
        # color limit in magnitudes
        ast_suppl_colorlimits["HST_WFC3_F475W"] = [["HST_WFC3_F814W",6]]
        ast_suppl_colorlimits["HST_WFC3_F336W"] = [["HST_WFC3_F475W",5], ["HST_WFC3_F814W",4]]

2020-11-10 16:00 UTC, karllark commented
Is this PR ready for merging?

2020-11-10 16:02 UTC, cmurray-astro commented
Yep!

2020-11-10 18:29 UTC, kmcquinn commented
Thanks! That is really helpful.

2020-11-10 19:06 UTC, merged